# Generated by Django 5.2.14 on 2026-05-13 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FederationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president_name', models.CharField(max_length=255, verbose_name='Имя президента')),
                ('president_birth_date', models.DateField(verbose_name='Дата рождения президента')),
                ('president_bio', models.TextField(verbose_name='Биография президента')),
                ('president_photo', models.ImageField(blank=True, null=True, upload_to='president_photos/', verbose_name='Фото президента')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Информация о Федерации',
                'verbose_name_plural': 'Информация о Федерации',
            },
        ),
        migrations.CreateModel(
            name='SportGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Группа', max_length=10)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='SportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Предмет', max_length=50)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Sportsmens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('year', models.SmallIntegerField(help_text='Год рождения')),
                ('sport_category', models.SmallIntegerField(help_text='Разряд')),
            ],
            options={
                'verbose_name': 'Спортсмен',
                'verbose_name_plural': 'Спортсмены',
            },
        ),
        migrations.CreateModel(
            name='Treners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(default='', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=10000)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autored_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='irina_app.news')),
            ],
        ),
        migrations.CreateModel(
            name='Starts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('event_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('registration_end_date', models.DateField(verbose_name='Дата окончания регистрации')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autored_starts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
                'ordering': ['event_date', 'registration_end_date'],
            },
        ),
        migrations.CreateModel(
            name='StartsСategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название', max_length=250)),
                ('starts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_of_starts', to='irina_app.starts')),
            ],
        ),
        migrations.CreateModel(
            name='StartsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_music', models.FileField(upload_to='audio/%Y/%m/', verbose_name='Файл (MP3)')),
                ('sport_groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='irina_app.sportgroups')),
                ('sport_item', models.ForeignKey(help_text='Выбранный предмет', on_delete=django.db.models.deletion.CASCADE, to='irina_app.sportitem')),
                ('sportsmam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_details', to='irina_app.sportsmens')),
                ('starts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_of_starts', to='irina_app.starts')),
                ('starts_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='irina_app.startsсategory')),
            ],
        ),
        migrations.AddField(
            model_name='sportsmens',
            name='trener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sportsmens_of_trener', to='irina_app.treners'),
        ),
    ]
