# Generated by Django 5.2.14 on 2026-05-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irina_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startsсategory',
            options={'verbose_name': 'Категория участников', 'verbose_name_plural': 'Категории участников'},
        ),
        migrations.AddField(
            model_name='startsсategory',
            name='available_items',
            field=models.ManyToManyField(blank=True, help_text='Доступные предметы для этой категории', related_name='categories', to='irina_app.sportitem'),
        ),
    ]
